"""CLEANUP — preview first, delete only what you can name.

Before loading real customer data the environment has to be cleared of test
records. The obvious implementation is a wipe, and the obvious implementation is
how you lose a customer. This codebase already had two wipes that do more than
they say:

  · `DELETE /admin/demo/wipe/{org_id}` is called "demo wipe" and deletes EVERY
    lead in the organization plus EVERY user whose role is 'advisor' - real ones
    included. There is no demo marker in the query at all.
  · `DELETE /sample-data/clear` has an inverted condition: when there are no
    sample leads it deletes every campaign the calling admin ever created.

So the rule here is the opposite of a wipe. Nothing is deleted unless this
module can say, per record, WHICH rule classified it as test data. If a row does
not match a rule, it survives - including rows that a test row points at.

THE RULES, and they are the only ones.

  is_test        `leads.is_test = TRUE`, the column that already exists for
                 exactly this purpose, plus its `test_note` explaining who
                 flagged it and why.
  sample_data    `leads.source_file = 'SAMPLE_DATA'`, written by the sample
                 generator so that its output can be removed surgically.
  import_batch   `leads.source_file = <a batch the operator names>`. Never
                 inferred - the operator picks the batch.
  demo_prefix    ids beginning with 'demo-', the convention the demo runner
                 already deletes by.
  orphaned       rows belonging to the platform pseudo-organization, which is
                 not a customer and whose rows therefore belong to nobody.

PROTECTED, ALWAYS. Platforms, brands, brand-sales organizations, real customer
organizations, canonical user identities, memberships, feature and permission
configuration, integration credentials, audit history, and schema. None of these
is classifiable as test data by any rule above, and none of them is deletable
through this service at all - not "unless you confirm", not at all. Deleting an
organization is a different operation with different consequences and it does
not belong behind a checkbox labelled "clean up test data".
"""

import json
from datetime import datetime
from typing import Any, Dict, List, Optional

from fastapi import HTTPException
from sqlalchemy import func, or_
from sqlalchemy.orm import Session

from app.models.models import (
    Organization, User, Lead, Message, Reply, LeadOutcome, CadenceState,
    EmailMessage, BookingLink, BookingFollowup, SurveyResponse,
    PipelineConversation, VoiceCall,
)
from app.services.platform_owner import GOD_PLATFORM_ORG_ID

# EVERY table that references leads.id, in delete order (children first).
#
# The first production run of this cleanup failed, and the failure is worth
# recording because the preview was also wrong.
#
# `pipeline_conversations.lead_id` and `voice_calls.lead_id` are NOT NULL with
# no ON DELETE CASCADE. Deleting a lead they point at raises IntegrityError. The
# exception escaped before the CORS middleware ran, so the browser reported
# "Failed to fetch" rather than a 500 - and because the transaction rolled back,
# nothing was deleted and a re-preview showed the same rows. Safe, but silent.
#
# The other four cascade at the database level, which is worse in a different
# way: they WOULD have been deleted, and the preview never counted them. An
# operator would have typed "DELETE 86 TEST RECORDS" and more than 86 rows would
# have gone. Every child is now both counted and deleted explicitly, so the
# number in the confirmation phrase is the number that actually disappears.
LEAD_CHILDREN = [
    ("outcomes", LeadOutcome),
    ("replies", Reply),
    ("messages", Message),
    ("cadence_state", CadenceState),
    ("email_messages", EmailMessage),        # CASCADE - was uncounted
    ("booking_links", BookingLink),          # CASCADE - was uncounted
    ("booking_followups", BookingFollowup),  # CASCADE - was uncounted
    ("survey_responses", SurveyResponse),    # CASCADE - was uncounted
    ("pipeline_conversations", PipelineConversation),  # NO CASCADE - blocked it
    ("voice_calls", VoiceCall),                        # NO CASCADE - blocked it
]

SAMPLE_TAG = "SAMPLE_DATA"
DEMO_PREFIX = "demo-"

RULES = {
    "is_test": "Flagged with leads.is_test = TRUE by an operator.",
    "sample_data": "Generated by the sample-data generator (source_file = '%s')." % SAMPLE_TAG,
    "import_batch": "Belongs to an import batch the operator named explicitly.",
    "demo_prefix": "Demo scenario record (id begins with '%s')." % DEMO_PREFIX,
    "orphaned": "Belongs to the platform placeholder organization, which is not a customer.",
}

# Named so the preview can show what it will NOT touch. Nothing in this list is
# reachable by any code path in this module.
PROTECTED = [
    "Platforms and white-label brands",
    "Brand sales organizations and their memberships",
    "Customer organizations (deleting one is a separate, deliberate operation)",
    "Canonical user identities and their memberships",
    "Feature entitlement and permission configuration",
    "Integration credentials and webhook secrets",
    "Audit history",
    "Database schema and migrations",
]


def _lead_filter(db: Session, rules: List[str], org_ids: Optional[List[str]],
                 import_batches: Optional[List[str]]):
    """Build the lead query from the SELECTED rules only. No rule, no rows."""
    q = db.query(Lead)
    if org_ids:
        q = q.filter(Lead.organization_id.in_(org_ids))

    clauses = []
    if "is_test" in rules:
        clauses.append(Lead.is_test.is_(True))
    if "sample_data" in rules:
        clauses.append(Lead.source_file == SAMPLE_TAG)
    if "demo_prefix" in rules:
        clauses.append(Lead.id.like(DEMO_PREFIX + "%"))
    if "orphaned" in rules:
        clauses.append(Lead.organization_id == GOD_PLATFORM_ORG_ID)
    if "import_batch" in rules and import_batches:
        clauses.append(Lead.source_file.in_(import_batches))

    if not clauses:
        # An empty rule set selects NOTHING. It must never fall through to
        # "everything", which is the failure mode of every wipe this replaces.
        return q.filter(Lead.id.is_(None))
    return q.filter(or_(*clauses))


def _why(lead: Lead, rules: List[str], import_batches: Optional[List[str]]) -> List[str]:
    out = []
    if "is_test" in rules and lead.is_test:
        out.append("is_test%s" % (" — %s" % lead.test_note if lead.test_note else ""))
    if "sample_data" in rules and lead.source_file == SAMPLE_TAG:
        out.append("sample_data")
    if "demo_prefix" in rules and (lead.id or "").startswith(DEMO_PREFIX):
        out.append("demo_prefix")
    if "orphaned" in rules and lead.organization_id == GOD_PLATFORM_ORG_ID:
        out.append("orphaned")
    if "import_batch" in rules and import_batches and lead.source_file in import_batches:
        out.append("import_batch — %s" % lead.source_file)
    return out


def _manifest(db: Session, leads: List[Lead], rules: List[str],
              import_batches: Optional[List[str]], org_names: Dict[str, str]) -> List[Dict[str, Any]]:
    """Per-record deletion manifest, built from THE SAME lead set that gets deleted.

    Not a separate query. A manifest assembled by re-deriving "what looks like
    test data" would be a second opinion, and the moment the two disagree the
    manifest is worse than none - it would describe a deletion that did not
    happen and omit one that did. This takes the rows `_lead_filter` already
    selected and counts what hangs off each of them.
    """
    ids = [l.id for l in leads]
    if not ids:
        return []

    def tally(model):
        out: Dict[str, int] = {}
        rows = (db.query(model.lead_id, func.count(model.id))
                .filter(model.lead_id.in_(ids)).group_by(model.lead_id).all())
        for lead_id, n in rows:
            out[lead_id] = n
        return out

    counts = {}
    for key, model in LEAD_CHILDREN:
        try:
            counts[key] = tally(model)
        except Exception:
            counts[key] = {}

    manifest = []
    for l in leads:
        dep = {key: counts[key].get(l.id, 0) for key, _m in LEAD_CHILDREN}
        manifest.append({
            "lead_id": l.id,
            "name": ("%s %s" % (l.first_name or "", l.last_name or "")).strip() or "(no name)",
            "organization_id": l.organization_id,
            "organization": org_names.get(l.organization_id, l.organization_id),
            "classification": _why(l, rules, import_batches),
            "source_file": l.source_file,
            "is_test": bool(l.is_test),
            "test_note": l.test_note,
            "status": l.status,
            "assigned_to_id": l.assigned_to_id,
            "dependents": dep,
            # The lead itself plus everything that goes with it.
            "total_records": 1 + sum(dep.values()),
        })
    return manifest


def preview(db: Session, *, rules: List[str], org_ids: Optional[List[str]] = None,
            import_batches: Optional[List[str]] = None,
            sample_limit: int = 15,
            include_manifest: bool = False) -> Dict[str, Any]:
    """What WOULD be deleted, by category, with the reason for each classification.

    Read-only. Runs the same query the delete runs, so the numbers shown are the
    numbers that happen - there is no second, more generous query behind the
    confirm button.
    """
    unknown = [r for r in rules if r not in RULES]
    if unknown:
        raise HTTPException(
            status_code=400,
            detail="Unknown cleanup rule(s): %s. Valid rules: %s"
                   % (", ".join(unknown), ", ".join(sorted(RULES))))

    leads = _lead_filter(db, rules, org_ids, import_batches).all()
    lead_ids = [l.id for l in leads]

    by_org: Dict[str, int] = {}
    for l in leads:
        by_org[l.organization_id] = by_org.get(l.organization_id, 0) + 1
    org_names = {
        o.id: o.name for o in db.query(Organization)
        .filter(Organization.id.in_(list(by_org) or [""])).all()
    }

    def count(model, attr="lead_id"):
        if not lead_ids:
            return 0
        return db.query(model).filter(getattr(model, attr).in_(lead_ids)).count()

    categories = [
        {
            "key": "leads", "label": "Leads / contacts",
            "count": len(leads),
            "scope": [{"organization_id": k, "name": org_names.get(k, k), "count": v}
                      for k, v in sorted(by_org.items(), key=lambda x: -x[1])],
            "why": sorted({w.split(" — ")[0] for l in leads
                           for w in _why(l, rules, import_batches)}),
            "dependencies": "Messages, replies, outcomes and cadence state below "
                            "belong to these leads and go with them.",
            "sample": [
                {"id": l.id, "name": ("%s %s" % (l.first_name or "", l.last_name or "")).strip(),
                 "organization_id": l.organization_id,
                 "source_file": l.source_file,
                 "why": _why(l, rules, import_batches)}
                for l in leads[:sample_limit]
            ],
        },
    ]
    LABELS = {
        "outcomes": "Lead outcomes", "replies": "Replies", "messages": "Messages",
        "cadence_state": "Cadence state", "email_messages": "Email messages",
        "booking_links": "Booking links", "booking_followups": "Booking follow-ups",
        "survey_responses": "Survey responses",
        "pipeline_conversations": "Pipeline conversations", "voice_calls": "Voice calls",
    }
    for key, model in LEAD_CHILDREN:
        categories.append({
            "key": key, "label": LABELS.get(key, key), "count": count(model),
            "scope": [], "why": ["child of a selected lead"],
            "dependencies": "Deleted with their lead.", "sample": [],
        })

    total = sum(c["count"] for c in categories)
    return {
        "rules_applied": [{"key": r, "description": RULES[r]} for r in rules],
        "org_ids": org_ids or [],
        "import_batches": import_batches or [],
        "categories": categories,
        "total_records": total,
        "protected": PROTECTED,
        "notes": [
            "Nothing is deleted by this call.",
            "Organizations, users, memberships and integrations are never "
            "deleted by cleanup, whatever is selected.",
            "A record that matches no rule survives, even if a deleted record "
            "referenced it.",
        ],
        # The exact string the operator must type. Includes the count, so a
        # stale preview cannot be used to confirm a bigger delete than the one
        # that was reviewed.
        "confirmation_phrase": "DELETE %d TEST RECORDS" % total,
        "manifest": (_manifest(db, leads, rules, import_batches, org_names)
                     if include_manifest else None),
        # Internal: the exact candidate ids. `record_plan` persists these so the
        # set that was reviewed can be compared with the set at execution time.
        # Stripped from the HTTP response by the router.
        "_lead_ids": [l.id for l in leads],
    }


def record_plan(db: Session, actor: User, *, rules: List[str],
                org_ids: Optional[List[str]], import_batches: Optional[List[str]],
                plan: Dict[str, Any]) -> "CleanupExecution":
    """Persist a preview as a durable, referenceable plan.

    Written on PREVIEW, not on execute, so the intent exists on disk before
    anything is destroyed. If the operator never confirms, the row simply stays
    `previewed` - a record that somebody looked, which is worth keeping too.
    """
    from app.models.cleanup_models import CleanupExecution, STATUS_PREVIEWED

    leads_cat = next((c for c in plan["categories"] if c["key"] == "leads"), {})
    row = CleanupExecution(
        actor_user_id=actor.id,
        actor_email=getattr(actor, "email", None),
        status=STATUS_PREVIEWED,
        rules=json.dumps(sorted(rules)),
        org_ids=json.dumps(org_ids or []),
        import_batches=json.dumps(import_batches or []),
        confirmation_phrase=plan["confirmation_phrase"],
        target_lead_ids=json.dumps(plan["_lead_ids"]),
        manifest=json.dumps(plan.get("manifest") or []),
        expected_counts=json.dumps({c["key"]: c["count"] for c in plan["categories"]}),
        expected_total=plan["total_records"],
        excluded=json.dumps(PROTECTED),
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def execute(db: Session, actor: User, *, rules: List[str],
            org_ids: Optional[List[str]] = None,
            import_batches: Optional[List[str]] = None,
            confirmation: str,
            execution_id: Optional[str] = None) -> Dict[str, Any]:
    """Delete exactly what the preview showed, or refuse - and record either way.

    The confirmation phrase carries the record count from the preview, so a
    confirmation typed against one preview cannot authorise a different, larger
    delete that happened to arrive in between.

    THE PLAN ROW IS WRITTEN AND COMMITTED BEFORE THE FIRST DELETE. That ordering
    is the whole design: if the delete then raises, the transaction that rolls
    back is the delete's, not the plan's, so the attempt survives its own
    failure. The first two production runs raised IntegrityError and left no
    trace at all; a cleanup system that only writes history on success will
    eventually let somebody believe a deletion happened that did not.
    """
    from app.routers.audit_log_router import log_action
    from app.models.cleanup_models import (
        CleanupExecution, STATUS_SUCCEEDED, STATUS_FAILED, STATUS_SUPERSEDED,
    )

    plan = preview(db, rules=rules, org_ids=org_ids, import_batches=import_batches,
                   include_manifest=True)
    expected = plan["confirmation_phrase"]

    row = None
    if execution_id:
        row = (db.query(CleanupExecution)
               .filter(CleanupExecution.id == execution_id).first())
        if row is None:
            raise HTTPException(status_code=404, detail="Cleanup plan not found")
        if row.actor_user_id != actor.id:
            raise HTTPException(status_code=404, detail="Cleanup plan not found")
        if row.status != "previewed":
            raise HTTPException(
                status_code=409,
                detail="This cleanup plan is already %s and cannot be run again."
                       % row.status)
        # The world may have moved between preview and confirm. Refuse rather
        # than delete a set the operator never saw.
        if set(json.loads(row.target_lead_ids)) != set(plan["_lead_ids"]):
            row.status = STATUS_SUPERSEDED
            row.error = ("The set of matching records changed between preview and "
                         "execution. Nothing was deleted; take a fresh preview.")
            db.commit()
            raise HTTPException(
                status_code=409,
                detail={"message": row.error, "execution_id": row.id})

    if (confirmation or "").strip() != expected:
        raise HTTPException(
            status_code=400,
            detail="Confirmation does not match. Type exactly: %s" % expected)

    if row is None:
        row = record_plan(db, actor, rules=rules, org_ids=org_ids,
                          import_batches=import_batches, plan=plan)
    row.confirmation_received = confirmation

    if plan["total_records"] == 0:
        row.status = STATUS_SUCCEEDED
        row.executed_at = datetime.utcnow()
        row.actual_counts = json.dumps({})
        row.actual_total = 0
        db.commit()
        return {"execution_id": row.id, "deleted": {}, "total_deleted": 0,
                "status": STATUS_SUCCEEDED, "expected_total": 0,
                "counts_match": True, "rules_applied": rules,
                "protected_untouched": PROTECTED,
                "message": "Nothing matched the selected rules. Nothing was deleted."}

    db.commit()   # the plan is now on disk, before anything is destroyed

    leads = _lead_filter(db, rules, org_ids, import_batches).all()
    lead_ids = [l.id for l in leads]

    deleted: Dict[str, int] = {}
    try:
        # Children first, in LEAD_CHILDREN order, every one of them explicit.
        # Relying on ON DELETE CASCADE for the four that have it would delete
        # rows this function never counted and never reported - the operator
        # would confirm one number and a larger one would happen.
        #
        # NOTE the absence of a per-table try/except here. An earlier version
        # swallowed each failure into `deleted[key] = 0`, which would have
        # reported a clean partial success for a delete that half-worked. One
        # failure now fails the whole thing, and the row records it.
        for key, model in LEAD_CHILDREN:
            deleted[key] = db.query(model).filter(
                model.lead_id.in_(lead_ids)).delete(synchronize_session=False)
        deleted["leads"] = db.query(Lead).filter(
            Lead.id.in_(lead_ids)).delete(synchronize_session=False)

        log_action(
            db, None, actor.id,
            action="data_cleanup.executed", target_type="cleanup",
            target_id=row.id,
            details={"execution_id": row.id, "rules": rules,
                     "org_ids": org_ids or [], "import_batches": import_batches or [],
                     "deleted": deleted, "confirmation": expected,
                     "lead_count": len(lead_ids)},
            note="Scoped test-data cleanup. Organizations, users, memberships and "
                 "integrations were not touched.",
            commit=False,
        )
        row.status = STATUS_SUCCEEDED
        row.executed_at = datetime.utcnow()
        row.actual_counts = json.dumps(deleted)
        row.actual_total = sum(deleted.values())
        db.commit()

    except Exception as exc:                              # noqa: BLE001
        # The delete is gone. The RECORD OF THE ATTEMPT must not be.
        db.rollback()
        fresh = (db.query(CleanupExecution)
                 .filter(CleanupExecution.id == row.id).first())
        if fresh is not None:
            fresh.status = STATUS_FAILED
            fresh.executed_at = datetime.utcnow()
            fresh.actual_counts = json.dumps({})
            fresh.actual_total = 0          # explicitly zero, never null-as-unknown
            fresh.error = "%s: %s" % (type(exc).__name__, str(exc)[:900])
            log_action(
                db, None, actor.id,
                action="data_cleanup.failed", target_type="cleanup",
                target_id=fresh.id,
                details={"execution_id": fresh.id, "rules": rules,
                         "error": fresh.error, "records_deleted": 0},
                note="Cleanup attempt failed and was rolled back. NOTHING was "
                     "deleted.",
                commit=False,
            )
            db.commit()
        raise HTTPException(
            status_code=500,
            detail={"message": "The cleanup failed and was rolled back. Nothing was "
                               "deleted.",
                    "execution_id": row.id,
                    "error": "%s: %s" % (type(exc).__name__, str(exc)[:300])})

    return {
        "execution_id": row.id,
        "status": row.status,
        "deleted": deleted,
        "total_deleted": row.actual_total,
        "expected_total": row.expected_total,
        "counts_match": row.actual_total == row.expected_total,
        "rules_applied": rules,
        "protected_untouched": PROTECTED,
    }
