"""CLEANUP — preview first, delete only what you can name.

Before loading real customer data the environment has to be cleared of test
records. The obvious implementation is a wipe, and the obvious implementation is
how you lose a customer. This codebase already had two wipes that do more than
they say:

  · `DELETE /admin/demo/wipe/{org_id}` is called "demo wipe" and deletes EVERY
    lead in the organization plus EVERY user whose role is 'advisor' - real ones
    included. There is no demo marker in the query at all.
  · `DELETE /sample-data/clear` has an inverted condition: when there are no
    sample leads it deletes every campaign the calling admin ever created.

So the rule here is the opposite of a wipe. Nothing is deleted unless this
module can say, per record, WHICH rule classified it as test data. If a row does
not match a rule, it survives - including rows that a test row points at.

THE RULES, and they are the only ones.

  is_test        `leads.is_test = TRUE`, the column that already exists for
                 exactly this purpose, plus its `test_note` explaining who
                 flagged it and why.
  sample_data    `leads.source_file = 'SAMPLE_DATA'`, written by the sample
                 generator so that its output can be removed surgically.
  import_batch   `leads.source_file = <a batch the operator names>`. Never
                 inferred - the operator picks the batch.
  demo_prefix    ids beginning with 'demo-', the convention the demo runner
                 already deletes by.
  orphaned       rows belonging to the platform pseudo-organization, which is
                 not a customer and whose rows therefore belong to nobody.

PROTECTED, ALWAYS. Platforms, brands, brand-sales organizations, real customer
organizations, canonical user identities, memberships, feature and permission
configuration, integration credentials, audit history, and schema. None of these
is classifiable as test data by any rule above, and none of them is deletable
through this service at all - not "unless you confirm", not at all. Deleting an
organization is a different operation with different consequences and it does
not belong behind a checkbox labelled "clean up test data".
"""

from typing import Any, Dict, List, Optional

from fastapi import HTTPException
from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.models.models import (
    Organization, User, Lead, Message, Reply, LeadOutcome, CadenceState,
)
from app.services.platform_owner import GOD_PLATFORM_ORG_ID

SAMPLE_TAG = "SAMPLE_DATA"
DEMO_PREFIX = "demo-"

RULES = {
    "is_test": "Flagged with leads.is_test = TRUE by an operator.",
    "sample_data": "Generated by the sample-data generator (source_file = '%s')." % SAMPLE_TAG,
    "import_batch": "Belongs to an import batch the operator named explicitly.",
    "demo_prefix": "Demo scenario record (id begins with '%s')." % DEMO_PREFIX,
    "orphaned": "Belongs to the platform placeholder organization, which is not a customer.",
}

# Named so the preview can show what it will NOT touch. Nothing in this list is
# reachable by any code path in this module.
PROTECTED = [
    "Platforms and white-label brands",
    "Brand sales organizations and their memberships",
    "Customer organizations (deleting one is a separate, deliberate operation)",
    "Canonical user identities and their memberships",
    "Feature entitlement and permission configuration",
    "Integration credentials and webhook secrets",
    "Audit history",
    "Database schema and migrations",
]


def _lead_filter(db: Session, rules: List[str], org_ids: Optional[List[str]],
                 import_batches: Optional[List[str]]):
    """Build the lead query from the SELECTED rules only. No rule, no rows."""
    q = db.query(Lead)
    if org_ids:
        q = q.filter(Lead.organization_id.in_(org_ids))

    clauses = []
    if "is_test" in rules:
        clauses.append(Lead.is_test.is_(True))
    if "sample_data" in rules:
        clauses.append(Lead.source_file == SAMPLE_TAG)
    if "demo_prefix" in rules:
        clauses.append(Lead.id.like(DEMO_PREFIX + "%"))
    if "orphaned" in rules:
        clauses.append(Lead.organization_id == GOD_PLATFORM_ORG_ID)
    if "import_batch" in rules and import_batches:
        clauses.append(Lead.source_file.in_(import_batches))

    if not clauses:
        # An empty rule set selects NOTHING. It must never fall through to
        # "everything", which is the failure mode of every wipe this replaces.
        return q.filter(Lead.id.is_(None))
    return q.filter(or_(*clauses))


def _why(lead: Lead, rules: List[str], import_batches: Optional[List[str]]) -> List[str]:
    out = []
    if "is_test" in rules and lead.is_test:
        out.append("is_test%s" % (" — %s" % lead.test_note if lead.test_note else ""))
    if "sample_data" in rules and lead.source_file == SAMPLE_TAG:
        out.append("sample_data")
    if "demo_prefix" in rules and (lead.id or "").startswith(DEMO_PREFIX):
        out.append("demo_prefix")
    if "orphaned" in rules and lead.organization_id == GOD_PLATFORM_ORG_ID:
        out.append("orphaned")
    if "import_batch" in rules and import_batches and lead.source_file in import_batches:
        out.append("import_batch — %s" % lead.source_file)
    return out


def preview(db: Session, *, rules: List[str], org_ids: Optional[List[str]] = None,
            import_batches: Optional[List[str]] = None,
            sample_limit: int = 15) -> Dict[str, Any]:
    """What WOULD be deleted, by category, with the reason for each classification.

    Read-only. Runs the same query the delete runs, so the numbers shown are the
    numbers that happen - there is no second, more generous query behind the
    confirm button.
    """
    unknown = [r for r in rules if r not in RULES]
    if unknown:
        raise HTTPException(
            status_code=400,
            detail="Unknown cleanup rule(s): %s. Valid rules: %s"
                   % (", ".join(unknown), ", ".join(sorted(RULES))))

    leads = _lead_filter(db, rules, org_ids, import_batches).all()
    lead_ids = [l.id for l in leads]

    by_org: Dict[str, int] = {}
    for l in leads:
        by_org[l.organization_id] = by_org.get(l.organization_id, 0) + 1
    org_names = {
        o.id: o.name for o in db.query(Organization)
        .filter(Organization.id.in_(list(by_org) or [""])).all()
    }

    def count(model, attr="lead_id"):
        if not lead_ids:
            return 0
        return db.query(model).filter(getattr(model, attr).in_(lead_ids)).count()

    categories = [
        {
            "key": "leads", "label": "Leads / contacts",
            "count": len(leads),
            "scope": [{"organization_id": k, "name": org_names.get(k, k), "count": v}
                      for k, v in sorted(by_org.items(), key=lambda x: -x[1])],
            "why": sorted({w.split(" — ")[0] for l in leads
                           for w in _why(l, rules, import_batches)}),
            "dependencies": "Messages, replies, outcomes and cadence state below "
                            "belong to these leads and go with them.",
            "sample": [
                {"id": l.id, "name": ("%s %s" % (l.first_name or "", l.last_name or "")).strip(),
                 "organization_id": l.organization_id,
                 "source_file": l.source_file,
                 "why": _why(l, rules, import_batches)}
                for l in leads[:sample_limit]
            ],
        },
        {"key": "messages", "label": "Messages", "count": count(Message),
         "scope": [], "why": ["child of a selected lead"],
         "dependencies": "Deleted with their lead.", "sample": []},
        {"key": "replies", "label": "Replies", "count": count(Reply),
         "scope": [], "why": ["child of a selected lead"],
         "dependencies": "Deleted with their lead.", "sample": []},
        {"key": "outcomes", "label": "Lead outcomes", "count": count(LeadOutcome),
         "scope": [], "why": ["child of a selected lead"],
         "dependencies": "Deleted with their lead.", "sample": []},
        {"key": "cadence_state", "label": "Cadence state", "count": count(CadenceState),
         "scope": [], "why": ["child of a selected lead"],
         "dependencies": "Deleted with their lead.", "sample": []},
    ]

    total = sum(c["count"] for c in categories)
    return {
        "rules_applied": [{"key": r, "description": RULES[r]} for r in rules],
        "org_ids": org_ids or [],
        "import_batches": import_batches or [],
        "categories": categories,
        "total_records": total,
        "protected": PROTECTED,
        "notes": [
            "Nothing is deleted by this call.",
            "Organizations, users, memberships and integrations are never "
            "deleted by cleanup, whatever is selected.",
            "A record that matches no rule survives, even if a deleted record "
            "referenced it.",
        ],
        # The exact string the operator must type. Includes the count, so a
        # stale preview cannot be used to confirm a bigger delete than the one
        # that was reviewed.
        "confirmation_phrase": "DELETE %d TEST RECORDS" % total,
    }


def execute(db: Session, actor: User, *, rules: List[str],
            org_ids: Optional[List[str]] = None,
            import_batches: Optional[List[str]] = None,
            confirmation: str) -> Dict[str, Any]:
    """Delete exactly what the preview showed, or refuse.

    The confirmation phrase carries the record count from the preview, so a
    confirmation typed against one preview cannot authorise a different, larger
    delete that happened to arrive in between.
    """
    from app.routers.audit_log_router import log_action
    from sqlalchemy import delete as sql_delete

    plan = preview(db, rules=rules, org_ids=org_ids, import_batches=import_batches)
    expected = plan["confirmation_phrase"]
    if (confirmation or "").strip() != expected:
        raise HTTPException(
            status_code=400,
            detail="Confirmation does not match. Type exactly: %s" % expected)

    if plan["total_records"] == 0:
        return {"deleted": {}, "total_deleted": 0,
                "message": "Nothing matched the selected rules. Nothing was deleted."}

    leads = _lead_filter(db, rules, org_ids, import_batches).all()
    lead_ids = [l.id for l in leads]

    deleted: Dict[str, int] = {}
    if lead_ids:
        deleted["outcomes"] = db.query(LeadOutcome).filter(
            LeadOutcome.lead_id.in_(lead_ids)).delete(synchronize_session=False)
        deleted["replies"] = db.query(Reply).filter(
            Reply.lead_id.in_(lead_ids)).delete(synchronize_session=False)
        deleted["messages"] = db.query(Message).filter(
            Message.lead_id.in_(lead_ids)).delete(synchronize_session=False)
        try:
            deleted["cadence_state"] = db.query(CadenceState).filter(
                CadenceState.lead_id.in_(lead_ids)).delete(synchronize_session=False)
        except Exception:
            deleted["cadence_state"] = 0
        deleted["leads"] = db.query(Lead).filter(
            Lead.id.in_(lead_ids)).delete(synchronize_session=False)

    log_action(
        db, None, actor.id,
        action="data_cleanup.executed", target_type="cleanup",
        target_id="rules:%s" % ",".join(sorted(rules)),
        details={"rules": rules, "org_ids": org_ids or [],
                 "import_batches": import_batches or [],
                 "deleted": deleted, "confirmation": expected},
        note="Scoped test-data cleanup. Organizations, users and integrations "
             "were not touched.",
        commit=False,
    )
    db.commit()

    return {
        "deleted": deleted,
        "total_deleted": sum(deleted.values()),
        "rules_applied": rules,
        "protected_untouched": PROTECTED,
    }
