"""SS1 + SS2 — EVERY PATH THAT CREATES A LEAD IS GATED, AND NO CEILING IS
IMPLICIT.

TWO CLAIMS, AND THE FIRST ONE IS STRUCTURAL.

CLAIM 1: there is no way into the `leads` table that skips the plan.

An entitlement model is only worth what its least-guarded entrance is worth. A
single unchecked path - a webhook, a scraper, an import, a seeding endpoint -
means the ceiling is advisory, and the customer who exceeds it does so through
whichever door nobody remembered. So rather than asserting it once about the
paths that existed on the day this was written, the test below WALKS THE
SOURCE: every function in app/ that constructs a `Lead` must reference the
capacity machinery, or be named in the fixtures list with a reason.

That list is the honest part. Demo seeding, simulation harnesses and proof
generators genuinely should not charge a customer's plan, and one of them -
`POST /admin/demo/seed/{org_id}` - proves the pattern by doing it correctly:
it calls `require_capacity` with a DECLARED, role-checked, audited
`bypass=BYPASS_DEMO_SEED` rather than simply not calling it. A bypass that is
written down is a decision; a missing call is an accident, and the two are
indistinguishable from the outside once the leads are in the table.

CLAIM 2: "unlimited" is only ever something somebody wrote down.

NULL means two different things in this schema and conflating them is how a
Custom customer became uncapped on every dimension. `limit_for` may return
None - unlimited - only from a published tier's own rate card or from a
snapshot that explicitly lists the dimension as unlimited. It must never
return None because nobody has configured the deal yet.
"""

import ast
import json
import os
from pathlib import Path

import pytest

from app.models.billing_models import BrandBillingPlan, CustomerEntitlementSnapshot
from app.models.models import Organization, Platform
from app.services import plan_limits

APP = Path(__file__).resolve().parents[1] / "app"

# Anything here that reads as "the plan was consulted".
CAPACITY_MARKERS = (
    "require_capacity", "require_capacity_user_initiated",
    "require_capacity_for_org_id", "hold_if_over_capacity",
    "counter_for_org_id", "has_room", "CapacityCounter",
)

# FIXTURES, NOT CUSTOMER BUSINESS. Each one states why it is not charged.
#
# The rule for being on this list: the rows it writes are generated by the
# platform to demonstrate or test itself, are disposable, and were not created
# by the customer. A path that writes a lead somebody could later work is NOT
# a fixture, whatever it is called.
FIXTURE_PATHS = {
    "scripts/seed_demo_org.py": "local seeding script, never runs in a request",
    "scripts/seed_god_mode_orgs.py": "local seeding script",
    "services/demo_environment.py": "the Demo Suite's own sandbox tenant",
    "services/demo_scenarios/customer_reactivation.py": "demo scenario fixture",
    "services/demo_scenarios/speed_to_lead.py": "demo scenario fixture",
    "services/ai_deployment/simulation.py": "simulation harness, synthetic org",
    "services/ai_operations/profiles.py": "synthetic profile for the harness",
    "services/workforce/profiles.py": "synthetic profile for the harness",
    "services/workforce/simulator.py": "the workforce simulator's own world",
    "services/workforce_intelligence/proof.py": "proof harness, synthetic org",
}


def _lead_creating_functions():
    """(relative path, function name, whether capacity is referenced)."""
    out = []
    for path in sorted(APP.rglob("*.py")):
        rel = str(path.relative_to(APP)).replace(os.sep, "/")
        if rel.startswith("models/"):
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:                                   # pragma: no cover
            continue
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            body = ast.dump(node)
            creates = any(
                isinstance(c, ast.Call) and getattr(c.func, "id", None) == "Lead"
                for c in ast.walk(node))
            if not creates:
                continue
            guarded = any(m in body for m in CAPACITY_MARKERS)
            out.append((rel, node.name, guarded))
    return out


# ── CLAIM 1 ─────────────────────────────────────────────────────────────────

def test_there_is_at_least_one_lead_creating_path_to_check():
    """A walker that silently matches nothing would pass forever."""
    assert len(_lead_creating_functions()) >= 10


def test_every_lead_creating_path_consults_the_plan():
    unguarded = [(rel, fn) for rel, fn, guarded in _lead_creating_functions()
                 if not guarded and rel not in FIXTURE_PATHS]
    assert not unguarded, (
        "these create a Lead without consulting plan capacity: %s\n"
        "If one of them is genuinely a fixture, add it to FIXTURE_PATHS with a "
        "reason. If it is a real customer path, gate it." % unguarded)


def test_the_fixture_list_has_not_gone_stale():
    """A path on the list that no longer creates leads is a claim nobody is
    checking any more."""
    live = {rel for rel, _, _ in _lead_creating_functions()}
    stale = [p for p in FIXTURE_PATHS if p not in live]
    assert not stale, "FIXTURE_PATHS names paths that no longer create leads: %s" % stale


def test_the_demo_seed_bypasses_by_declaration_not_by_omission():
    """The pattern every fixture path should follow if it ever charges a real
    organization: a named reason, role-checked and audited."""
    src = (APP / "routers" / "admin_router.py").read_text(encoding="utf-8")
    assert "bypass=plan_limits.BYPASS_DEMO_SEED" in src
    assert plan_limits.BYPASS_DEMO_SEED in plan_limits.BYPASS_REASONS


def test_a_bypass_reason_must_be_declared():
    """An undeclared reason is refused rather than honoured."""
    assert "not_a_real_reason" not in plan_limits.BYPASS_REASONS


# ── CLAIM 2 ─────────────────────────────────────────────────────────────────

def _brand(db_session, slug="matrix-brand"):
    p = Platform(name="Matrix Brand", slug=slug)
    db_session.add(p); db_session.commit(); return p


def _plans(db_session, platform):
    rows = [
        BrandBillingPlan(platform_id=platform.id, key="starter", name="Starter",
                         max_leads=1000, max_users=1, is_purchasable=True,
                         is_active=True, currency="usd", sort_order=10),
        BrandBillingPlan(platform_id=platform.id, key="enterprise", name="Custom",
                         max_leads=None, max_users=None, is_purchasable=False,
                         requires_entitlement_policy=True, is_active=True,
                         currency="usd", sort_order=40),
    ]
    db_session.add_all(rows); db_session.commit(); return rows


def _org(db_session, platform, key, slug="matrix-org"):
    org = Organization(name="Matrix Co", slug=slug, plan=key,
                       billing_plan_key=key, platform_id=platform.id)
    db_session.add(org); db_session.commit(); return org


def test_an_unconfigured_custom_deal_is_not_unlimited(db_session):
    """The whole of SS2 in one assertion."""
    brand = _brand(db_session)
    _plans(db_session, brand)
    org = _org(db_session, brand, "enterprise")
    for key in (plan_limits.LIMIT_LEADS, plan_limits.LIMIT_USERS):
        assert plan_limits.limit_for(db_session, org, key) is not None, (
            "an unconfigured Custom deal resolved to unlimited on %s" % key)


def test_an_unconfigured_custom_deal_says_so_rather_than_claiming_a_tier(db_session):
    brand = _brand(db_session, slug="matrix-brand-2")
    _plans(db_session, brand)
    org = _org(db_session, brand, "enterprise", slug="matrix-org-2")
    state = plan_limits.entitlement_state(db_session, org)
    blob = json.dumps(state).lower()
    assert "needs configuration" in blob or "needs_configuration" in blob


def test_unlimited_is_only_ever_written_down(db_session):
    """A dimension is uncapped because an agreement SAYS it is."""
    brand = _brand(db_session, slug="matrix-brand-3")
    _plans(db_session, brand)
    org = _org(db_session, brand, "enterprise", slug="matrix-org-3")
    snap = CustomerEntitlementSnapshot(
        organization_id=org.id, max_leads=None, max_users=None,
        unlimited_json=json.dumps([plan_limits.LIMIT_LEADS]))
    db_session.add(snap); db_session.commit()

    # Stated unlimited -> unlimited.
    assert plan_limits.limit_for(db_session, org, plan_limits.LIMIT_LEADS) is None
    # Not stated -> still a number, not silence.
    assert plan_limits.limit_for(db_session, org, plan_limits.LIMIT_USERS) is not None


def test_a_recorded_ceiling_overrides_the_tier_rather_than_being_ignored(db_session):
    """SS1. The snapshot used to be consulted only for an org with NO tier, so
    the one supported way to record a negotiated ceiling was stored and then
    ignored for nearly every customer."""
    brand = _brand(db_session, slug="matrix-brand-4")
    _plans(db_session, brand)
    org = _org(db_session, brand, "starter", slug="matrix-org-4")
    assert plan_limits.limit_for(db_session, org, plan_limits.LIMIT_LEADS) == 1000

    db_session.add(CustomerEntitlementSnapshot(
        organization_id=org.id, max_leads=7500, max_users=None))
    db_session.commit()
    assert plan_limits.limit_for(db_session, org, plan_limits.LIMIT_LEADS) == 7500
    # Per dimension: the snapshot said nothing about users, so the tier stands.
    assert plan_limits.limit_for(db_session, org, plan_limits.LIMIT_USERS) == 1


def test_require_capacity_actually_refuses(db_session):
    """The matrix's FAILURE BEHAVIOR column, asserted rather than assumed:
    402 Payment Required, not 403 - the caller is not unauthorized, their plan
    does not include it."""
    from fastapi import HTTPException
    brand = _brand(db_session, slug="matrix-brand-5")
    _plans(db_session, brand)
    org = _org(db_session, brand, "starter", slug="matrix-org-5")
    with pytest.raises(HTTPException) as caught:
        plan_limits.require_capacity(db_session, org, plan_limits.LIMIT_LEADS,
                                     adding=10_000)
    assert caught.value.status_code == 402


def test_a_held_lead_is_blocked_on_every_channel(db_session, sample_org,
                                                 sample_advisor):
    """Capacity is not only an intake rule. A held lead must not be worked,
    or a plan ceiling quietly becomes a Twilio and Resend bill."""
    from app.models.models import Lead
    from app.services import lead_capacity
    from app.services.compliance_service import check_compliance_preflight
    lead = Lead(organization_id=sample_org.id, assigned_to_id=sample_advisor.id,
                first_name="Held", last_name="Lead", phone="12145550123",
                email="held@example.com", status="new",
                capacity_state=lead_capacity.OVER_CAPACITY)
    db_session.add(lead); db_session.commit()
    assert lead_capacity.is_held(lead) is True

    for channel in ("sms", "email"):
        with pytest.raises(ValueError, match="capacity"):
            check_compliance_preflight(db_session, lead, channel=channel)


def test_a_lead_that_is_not_held_is_not_blocked_by_capacity(
        db_session, sample_org, sample_advisor):
    """The assertion above would pass just as well against a preflight that
    refused everything."""
    from app.models.models import Lead
    from app.services.compliance_service import check_compliance_preflight
    lead = Lead(organization_id=sample_org.id, assigned_to_id=sample_advisor.id,
                first_name="Free", last_name="Lead", phone="12145550124",
                email="free@example.com", status="new")
    db_session.add(lead); db_session.commit()
    assert check_compliance_preflight(db_session, lead, channel="sms") is None
    assert check_compliance_preflight(db_session, lead, channel="email") is None
