"""initial_schema

Revision ID: 02907fcdb80c
Revises:
Create Date: 2026-08-21 01:14:14.711126

NOTE: This migration cleans up schema drift — 4 orphaned tables and ~30 columns
that were removed from the SQLAlchemy models but never cleaned up from the DB.
Orphaned tables: crm_connections, crm_contact_notes, auto_send_queue, appointment_case_files
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02907fcdb80c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — remove orphaned tables and columns that no longer exist in models."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_connections')
    op.drop_table('crm_contact_notes')
    op.drop_table('auto_send_queue')
    op.drop_table('appointment_case_files')
    op.drop_column('booking_links', 'confirmed_at')
    op.drop_column('campaigns', 'tone')
    op.drop_column('campaigns', 'error_count')
    op.drop_column('campaigns', 'sent_count')
    op.drop_column('campaigns', 'skipped_count')
    op.drop_column('campaigns', 'purpose')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'ai_direction')
    op.drop_column('campaigns', 'sent_at')
    op.drop_column('crm_contacts', 'company')
    op.drop_column('crm_contacts', 'pipeline_stage')
    op.drop_column('crm_contacts', 'last_contact_at')
    op.drop_index(op.f('ix_email_messages_lead_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sender_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_sent_at'), table_name='email_messages')
    op.drop_column('email_messages', 'click_count')
    op.drop_column('email_messages', 'opened_at')
    op.drop_column('email_messages', 'last_clicked_at')
    op.drop_column('lead_outcomes', 'is_veteran')
    op.drop_column('lead_outcomes', 'has_insurance_funding')
    op.drop_column('lead_outcomes', 'next_step')
    op.drop_column('lead_outcomes', 'has_preneed_planning')
    op.drop_index(op.f('ix_leads_org_created'), table_name='leads')
    op.drop_index(op.f('ix_leads_org_import_list'), table_name='leads')
    op.drop_index(op.f('ix_leads_org_last_messaged'), table_name='leads')
    op.drop_index(op.f('ix_leads_org_temp'), table_name='leads')
    op.drop_index(op.f('ix_leads_org_tier'), table_name='leads')
    op.drop_index(op.f('ix_leads_org_updated'), table_name='leads')
    op.drop_column('leads', 'google_contact_resource_name')
    op.drop_column('leads', 'service_address')
    op.drop_column('leads', 'extra_data')
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_lead_sent'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_column('notifications', 'send_failure_reason')
    op.drop_column('organizations', 'twilio_a2p_campaign_sid')
    op.drop_column('organizations', 'meta_app_secret')
    op.drop_column('organizations', 'meta_webhook_verify_token')
    op.drop_column('organizations', 'tiktok_webhook_secret')
    op.drop_column('organizations', 'meta_page_access_token')
    op.drop_column('organizations', 'twilio_messaging_service_sid')
    op.drop_column('organizations', 'twilio_a2p_brand_status')
    op.drop_column('organizations', 'twilio_a2p_campaign_use_case')
    op.drop_column('organizations', 'twilio_a2p_campaign_status')
    op.drop_column('organizations', 'twilio_a2p_brand_sid')
    op.drop_column('organizations', 'twilio_a2p_registered_at')
    op.drop_column('organizations', 'social_webhook_token')
    op.drop_index(op.f('ix_replies_lead_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_lead_received'), table_name='replies')
    op.drop_index(op.f('ix_replies_received_at'), table_name='replies')
    op.drop_column('users', 'feature_flags')
    op.drop_column('users', 'notification_phone')
    op.drop_column('users', 'notify_via_sms')
    op.drop_column('users', 'can_import_leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema — restore orphaned tables and columns."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_import_leads', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notify_via_sms', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notification_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('feature_flags', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_replies_received_at'), 'replies', ['received_at'], unique=False)
    op.create_index(op.f('ix_replies_lead_received'), 'replies', ['lead_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_index(op.f('ix_replies_lead_id'), 'replies', ['lead_id'], unique=False)
    op.add_column('organizations', sa.Column('social_webhook_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_brand_sid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_campaign_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_campaign_use_case', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_brand_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_messaging_service_sid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('meta_page_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('tiktok_webhook_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('meta_webhook_verify_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('meta_app_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('twilio_a2p_campaign_sid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('send_failure_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_lead_sent'), 'messages', ['lead_id', sa.literal_column('sent_at DESC')], unique=False)
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    op.add_column('leads', sa.Column('extra_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('service_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('google_contact_resource_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_leads_org_updated'), 'leads', ['organization_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('ix_leads_org_tier'), 'leads', ['organization_id', 'tier'], unique=False)
    op.create_index(op.f('ix_leads_org_temp'), 'leads', ['organization_id', 'engagement_temperature'], unique=False)
    op.create_index(op.f('ix_leads_org_last_messaged'), 'leads', ['organization_id', sa.literal_column('last_messaged_at DESC')], unique=False)
    op.create_index(op.f('ix_leads_org_import_list'), 'leads', ['organization_id', 'import_list_name'], unique=False)
    op.create_index(op.f('ix_leads_org_created'), 'leads', ['organization_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('lead_outcomes', sa.Column('has_preneed_planning', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lead_outcomes', sa.Column('next_step', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lead_outcomes', sa.Column('has_insurance_funding', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lead_outcomes', sa.Column('is_veteran', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('email_messages', sa.Column('last_clicked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_messages', sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('email_messages', sa.Column('click_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_email_messages_sent_at'), 'email_messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_messages_sender_id'), 'email_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_email_messages_lead_id'), 'email_messages', ['lead_id'], unique=False)
    op.add_column('crm_contacts', sa.Column('last_contact_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('crm_contacts', sa.Column('pipeline_stage', sa.VARCHAR(), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True))
    op.add_column('crm_contacts', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ai_direction', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('skipped_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('sent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('error_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_links', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('appointment_case_files',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('lead_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('recorded_by_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('booking_link_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('appointment_type', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('outcome_type', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('products_discussed', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('products_sold', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('policy_carrier', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('policy_number', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('coverage_amount', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('premium_monthly', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('premium_annual', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('application_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('issue_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('chk_id_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_beneficiary_named', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_app_signed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_payment_collected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_illustrations_reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_medical_history', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_hipaa_signed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_replacement_form', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_beneficiary_reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('chk_riders_explained', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('advisor_notes', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('objections_raised', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('client_concerns', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('referral_potential', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.Column('referral_notes', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('case_status', sa.VARCHAR(), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
        sa.Column('next_action', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('next_action_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('next_action_notes', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('crm_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('crm_sync_status', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('crm_external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('crm_error', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('appointment_case_files_pkey'))
    )
    op.create_table('auto_send_queue',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('lead_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('advisor_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('source_ref', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('ai_reason', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('actioned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('actioned_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['actioned_by_id'], ['users.id'], name=op.f('auto_send_queue_actioned_by_id_fkey')),
        sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], name=op.f('auto_send_queue_advisor_id_fkey')),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('auto_send_queue_lead_id_fkey')),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('auto_send_queue_organization_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('auto_send_queue_pkey'))
    )
    op.create_table('crm_contact_notes',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('contact_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name=op.f('crm_contact_notes_contact_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('crm_contact_notes_created_by_id_fkey')),
        sa.PrimaryKeyConstraint('id', name=op.f('crm_contact_notes_pkey'))
    )
    op.create_table('crm_connections',
        sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('crm_type', sa.VARCHAR(), server_default=sa.text("'webhook'::character varying"), autoincrement=False, nullable=False),
        sa.Column('webhook_url', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('webhook_secret', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('api_key_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('api_base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('sync_mode', sa.VARCHAR(), server_default=sa.text("'push_only'::character varying"), autoincrement=False, nullable=True),
        sa.Column('push_events', sa.TEXT(), server_default=sa.text('\'["booking","status_change"]\'::text'), autoincrement=False, nullable=True),
        sa.Column('annotation_tag', sa.VARCHAR(), server_default=sa.text("'BookaBoost'::character varying"), autoincrement=False, nullable=True),
        sa.Column('field_mapping', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
        sa.Column('last_push_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('last_pull_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column('total_pushed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
        sa.Column('total_pulled', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('crm_connections_pkey'))
    )
    # ### end Alembic commands ###
