"""The migration step. A deploy gate, not a side effect of booting.

    python -m app.migrate

═══════════════════════════════════════════════════════════════════════════
WHY THIS EXISTS
═══════════════════════════════════════════════════════════════════════════
Schema changes used to happen inside the web application's startup handler.
That put every deploy in a position where the only way to find out whether
the schema could be changed was to try to boot — and if the answer was no,
the answer arrived as "Waiting for application startup" for fifteen minutes,
followed by Render tearing down the healthy old instance.

The deployment model that replaces it:

    MIGRATION STEP  →  MIGRATION SUCCEEDS  →  APP STARTS

Render runs this as the service's `preDeployCommand`. A non-zero exit aborts
the deploy BEFORE the new instance is started and BEFORE the old one is
retired, so a database that cannot take the change costs a failed deploy and
a clear message rather than an outage.

═══════════════════════════════════════════════════════════════════════════
WHY THIS IS NOT ALEMBIC (YET), AND WHAT WOULD HAVE HAPPENED IF IT WERE
═══════════════════════════════════════════════════════════════════════════
Alembic IS present, with six revisions — and it is six revisions behind a
schema that `auto_migrate` has carried to 369 columns. `alembic upgrade head`
against production today would do almost nothing, because production is far
ahead of the last revision.

The tempting move is to autogenerate one big catch-up revision and switch. It
was not taken, for a reason that matters more than tidiness: an autogenerated
revision against a live schema is a DROP statement generator. Anything the
models no longer mention — a column kept deliberately, like `deal_value`, or
one another service still writes — becomes a `drop_column` nobody reviews
carefully at deploy time. Trading a startup hang for a data-loss risk is not
hardening.

So the transition is incremental and the ORDER is the part being fixed now:
this step owns migrations, runs them before the app exists, and fails the
deploy on its own. The engine underneath is still `auto_migrate`. Moving that
engine to Alembic afterwards is a mechanical change to ONE function, and it
can be done with the deploy gate already in place instead of while also
inventing it.

WHAT THIS STEP WILL NOT DO. It never terminates a session, never cancels a
query, never drops anything. When the database is not in a state to be
migrated it says so and exits non-zero. Recovery stays a deliberate act.
"""

import logging
import os
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [migrate] %(levelname)s %(message)s",
)
log = logging.getLogger("migrate")

EXIT_OK = 0
EXIT_PREFLIGHT_BLOCKED = 2
EXIT_REQUIRED_SCHEMA_MISSING = 3
EXIT_FAILED = 4


def _report_preflight(report: dict) -> None:
    log.info("preflight: reachable=%s idle_in_transaction_over_threshold=%s "
             "lock_waits_over_threshold=%s connections=%s/%s",
             report.get("reachable"),
             report["idle_in_transaction"]["over_threshold"],
             report["lock_waits"]["over_threshold"],
             report["connections"].get("used"),
             report["connections"].get("limit"))
    for b in report.get("blockers", []):
        log.error("preflight BLOCKED [%s] %s", b["code"], b["message"])
        log.error("preflight ACTION  [%s] %s", b["code"], b["action"])


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    skip_preflight = "--skip-preflight" in argv

    # Imported here rather than at module scope so that `--help`-style misuse
    # and import errors are distinguishable from database failures.
    from app.auto_migrate import (LAST_RUN, RequiredSchemaMissing,
                                  run_auto_migrations)
    from app.deps import engine
    # THE SAME REGISTRY main.py USES, not a second list. `create_all` only
    # creates tables whose model module has been imported, so a migration step
    # with its own import list would silently stop creating whole families of
    # tables the day somebody adds a model and updates only one of the two
    # places. `app.models.registry` exists precisely so there is one.
    import app.models.registry  # noqa: F401  (imported for side effects)
    from app.models.models import Base
    from app.services import db_health

    # ── 1. PREFLIGHT: is the database in a state to be changed? ───────────
    #
    # READ-ONLY. It reports and refuses; it never clears the way for itself.
    if not skip_preflight:
        report = db_health.preflight(engine)
        _report_preflight(report)
        if not report["safe_to_migrate"]:
            log.error("Refusing to migrate. Nothing was changed. "
                      "Resolve the conditions above and deploy again.")
            return EXIT_PREFLIGHT_BLOCKED
    else:
        # An explicit escape hatch for the case where a human has looked at
        # the evidence and decided to proceed anyway. It is a flag on the
        # command, not an environment variable, so it cannot become the
        # permanent default by accident.
        log.warning("Preflight skipped by --skip-preflight.")

    # ── 2. CREATE ANY WHOLE NEW TABLES ────────────────────────────────────
    # Same call the app made at startup, in the same order, so this step is
    # not a second opinion about what the schema should be.
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as e:                                   # noqa: BLE001
        log.exception("create_all failed")
        log.error("Migration aborted: %s", str(e)[:300])
        return EXIT_FAILED

    # ── 3. COLUMNS, ENUMS, INDEXES ────────────────────────────────────────
    try:
        run_auto_migrations(engine)
    except RequiredSchemaMissing as e:
        # The one condition that must stop a deploy dead. Reported here with
        # the full explanation the exception carries, because this log line
        # is what somebody reads at 2am.
        log.error("%s", e)
        return EXIT_REQUIRED_SCHEMA_MISSING
    except Exception as e:                                   # noqa: BLE001
        log.exception("migration step failed")
        log.error("Migration aborted: %s", str(e)[:300])
        return EXIT_FAILED

    # ── 4. SAY WHAT HAPPENED ──────────────────────────────────────────────
    log.info("migration outcome=%s elapsed=%ss columns_checked=%s",
             LAST_RUN["outcome"], LAST_RUN["elapsed_seconds"],
             LAST_RUN["columns_checked"])
    if LAST_RUN["missing_optional"]:
        # NOT a deploy failure, and the reason is stated rather than implied:
        # these break one screen, and blocking every deploy on them would
        # hand a contended unrelated table the power to stop all shipping.
        log.warning("DEGRADED: %d non-core column(s) still missing: %s. "
                    "The application will start; features touching them will "
                    "fail until a later run applies them.",
                    len(LAST_RUN["missing_optional"]),
                    ", ".join(LAST_RUN["missing_optional"]))
    log.info("Migration step complete. Starting the application is safe.")
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
