import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, getCurrentUser } from '../api/client'
import { workspaceRole } from '../auth/workspaceAuthority'
import '../styles/sciWorkspace.css'

const FEED_LIMIT = 300
import '../styles/shared.css'

const DELIVERY_CONFIG = {
  delivered:   { label: '✓ Delivered',   color: 'var(--signal-green)',  bg: 'var(--pill-success-bg)', border: 'var(--pill-success-bd)' },
  sent:        { label: '✓ Sent',         color: 'var(--signal-green)',  bg: 'var(--pill-success-bg)', border: 'var(--pill-success-bd)' },
  pending:     { label: '⏳ Pending',      color: 'var(--signal-amber)',  bg: 'var(--pill-warning-bg)', border: 'var(--pill-warning-bd)' },
  queued:      { label: '⏳ Queued',       color: 'var(--signal-amber)',  bg: 'var(--pill-warning-bg)', border: 'var(--pill-warning-bd)' },
  sending:     { label: '⏳ Sending',      color: 'var(--signal-amber)',  bg: 'var(--pill-warning-bg)', border: 'var(--pill-warning-bd)' },
  failed:      { label: '✗ Failed',        color: 'var(--signal-red)',    bg: 'var(--pill-danger-bg)',  border: 'var(--pill-danger-bd)' },
  undelivered: { label: '✗ Undelivered',  color: 'var(--signal-red)',    bg: 'var(--pill-danger-bg)',  border: 'var(--pill-danger-bd)' },
}

function DeliveryBadge({ status }) {
  const cfg = DELIVERY_CONFIG[status] || DELIVERY_CONFIG.pending
  return (
    <span style={{
      fontSize: 11, borderRadius: 4, padding: '2px 7px', whiteSpace: 'nowrap',
      color: cfg.color, background: cfg.bg, border: `1px solid ${cfg.border}`,
    }}>
      {cfg.label}
    </span>
  )
}

// SS4: rows flagged ai_generated by the backend (send_source vocabulary).
function AiBadge({ item }) {
  if (!item?.ai_generated) return null
  return (
    <span
      title={item.send_source_label ? `AI-generated · ${item.send_source_label}` : 'AI-generated'}
      style={{
        marginLeft: 6, fontSize: 10, fontWeight: 700,
        background: 'var(--pill-info-bg)', color: 'var(--pill-info-fg)',
        border: '1px solid var(--pill-info-bd)', borderRadius: 3, padding: '1px 5px',
      }}
    >
      AI
    </span>
  )
}

const TODAY_LIST_LIMIT = 50

// SS3: today's sends, counted by the server (/activity/today) against the
// organization's own day boundary rather than filtered from the 30-day page.
function TodaySummary({ today, loading, error, onRetry, navigate }) {
  const [open, setOpen] = useState(false)
  if (loading && !today) {
    return <div className="panel" style={{ marginBottom: 16, padding: '12px 16px', fontSize: 13, color: 'var(--text-secondary)' }}>Loading today…</div>
  }
  if (error && !today) {
    return (
      <div className="panel" style={{ marginBottom: 16, padding: '12px 16px', fontSize: 13, display: 'flex', gap: 12, alignItems: 'center' }}>
        <span style={{ flex: 1, color: 'var(--signal-red)' }}>⚠ Couldn't load today's activity: {error}</span>
        <button className="btn btn--secondary" style={{ fontSize: 12, padding: '4px 12px' }} onClick={onRetry}>↻ Retry</button>
      </div>
    )
  }
  if (!today) return null
  const byChannel = today.by_channel || {}
  const items = today.items || []
  const aiCount = items.filter((i) => i.ai_generated).length
  return (
    <section className="panel" style={{ marginBottom: 16, padding: '12px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
        <strong style={{ fontSize: 14 }}>Today</strong>
        <span style={{ fontSize: 13 }}><strong>{today.total ?? 0}</strong> sent</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>📱 SMS {byChannel.sms || 0}</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>✉️ Email {byChannel.email || 0}</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
          {today.leads_contacted ?? 0} leads
          {today.contacted_more_than_once > 0 && ` · ${today.contacted_more_than_once} more than once`}
        </span>
        {aiCount > 0 && (
          <span style={{ fontSize: 13, color: 'var(--color-primary)' }}>
            {aiCount} AI{items.length < (today.total || 0) ? ' (shown)' : ''}
          </span>
        )}
        {today.timezone && (
          <span style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>{today.timezone}</span>
        )}
        {items.length > 0 && (
          <button
            className="btn btn--secondary"
            style={{ fontSize: 12, padding: '4px 12px', marginLeft: 'auto' }}
            onClick={() => setOpen(!open)}
          >
            {open ? 'Hide list ▲' : `Show list ▼`}
          </button>
        )}
      </div>
      {open && items.length > 0 && (
        <div style={{ marginTop: 10, maxHeight: 260, overflowY: 'auto' }}>
          {items.map((item) => (
            <div
              key={`${item.channel}-${item.id}`}
              style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 12, padding: '4px 0', borderTop: '1px solid var(--border-subtle)' }}
            >
              <span>{item.channel === 'sms' ? '📱' : '✉️'}</span>
              <span
                style={{ fontWeight: 600, cursor: 'pointer', color: 'var(--accent)' }}
                onClick={() => navigate(`/leads/${item.lead_id}`)}
              >
                {item.lead_name}
              </span>
              <AiBadge item={item} />
              {item.touches_today > 1 && (
                <span style={{ fontSize: 10, color: 'var(--signal-amber)' }}>×{item.touches_today}</span>
              )}
              <span style={{ flex: 1, color: 'var(--text-secondary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {item.preview || '—'}
              </span>
              <span style={{ color: 'var(--text-tertiary)', whiteSpace: 'nowrap' }}>{formatTime(item.sent_at)}</span>
            </div>
          ))}
          {today.returned < today.total && (
            <div style={{ fontSize: 11, color: 'var(--text-tertiary)', paddingTop: 4 }}>
              Showing {today.returned} of {today.total}.
            </div>
          )}
        </div>
      )}
    </section>
  )
}

function formatTime(isoStr) {
  if (!isoStr) return '—'
  const d = new Date(isoStr)
  const now = new Date()
  const today = now.toDateString() === d.toDateString()
  const yesterday = new Date(now - 86400000).toDateString() === d.toDateString()
  const timeStr = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  if (today) return `Today ${timeStr}`
  if (yesterday) return `Yesterday ${timeStr}`
  return d.toLocaleDateString([], { month: 'short', day: 'numeric' }) + ' ' + timeStr
}

// ── ACTIVITY & CALL HISTORY (Oct 2026) ──────────────────────────────────────
// GET /activity/feed: texts and emails both ways, calls and voicemails, each
// once, in the same lead scope as every other screen. Filters run on the
// loaded window. Source ids appear only for admins, in a closed drawer.
const FEED_KIND_LABEL = { sms: 'Text', email: 'Email', voice: 'Call' }
const ACTOR_LABEL = { ai: 'AI', human: 'Person', system: 'Automation', customer: 'Customer' }

function feedWhen(iso) {
  if (!iso) return ''
  const d = new Date(/[zZ]|[+-]\d\d:?\d\d$/.test(iso) ? iso : iso + 'Z')
  return Number.isNaN(d.getTime()) ? '' : d.toLocaleString([], { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit', timeZoneName: 'short' })
}

function ActivityFeed({ navigate }) {
  const [days, setDays] = useState(30)
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [channel, setChannel] = useState('all')
  const [direction, setDirection] = useState('all')
  const [actor, setActor] = useState('all')
  const [outcome, setOutcome] = useState('all')
  const [q, setQ] = useState('')
  const [open, setOpen] = useState(null)
  const role = workspaceRole(getCurrentUser())
  const isAdmin = role === 'org_admin' || role === 'super_admin' || role === 'god_admin'

  function load() {
    setError('')
    setData(null)
    api.get('/activity/feed', { params: { days, limit: 500 } })
      .then(setData).catch(e => setError(e.message || 'Could not load activity.'))
  }
  useEffect(() => { load() }, [days])  // eslint-disable-line react-hooks/exhaustive-deps

  const items = (data?.items || []).filter(i => {
    if (channel !== 'all' && i.channel !== channel) return false
    if (direction !== 'all' && i.direction !== direction) return false
    if (actor !== 'all' && i.actor !== actor) return false
    if (outcome === 'failed' && !/fail|undeliver|bounce/i.test(i.result || '')) return false
    if (outcome === 'voicemail' && !(i.kind === 'voicemail' || i.voicemail_left)) return false
    if (q.trim()) {
      const s = q.trim().toLowerCase()
      return [i.lead_name, i.lead_phone, i.lead_email, i.summary].filter(Boolean).join(' ').toLowerCase().includes(s)
    }
    return true
  })
  const sel = (label, value, set, opts) => (
    <select className="filter-select" aria-label={label} value={value} onChange={e => set(e.target.value)}>
      {opts.map(([v, l]) => <option key={v} value={v}>{l}</option>)}
    </select>
  )

  return (
    <section className="panel act-feed" aria-label="Activity and call history">
      <div className="act-filters">
        <input type="search" className="search-input" placeholder="Search contact or message" aria-label="Search activity"
          value={q} onChange={e => setQ(e.target.value)} />
        {sel('Channel', channel, setChannel, [['all', 'All channels'], ['sms', 'Texts'], ['email', 'Emails'], ['voice', 'Calls & voicemail']])}
        {sel('Direction', direction, setDirection, [['all', 'In & out'], ['inbound', 'Inbound'], ['outbound', 'Outbound']])}
        {sel('Who', actor, setActor, [['all', 'Anyone'], ['customer', 'Customer'], ['human', 'Person on our side'], ['ai', 'AI'], ['system', 'Automation']])}
        {sel('Outcome', outcome, setOutcome, [['all', 'Any outcome'], ['failed', 'Failed only'], ['voicemail', 'Voicemail']])}
        {sel('Date range', String(days), v => setDays(Number(v)), [['7', 'Last 7 days'], ['30', 'Last 30 days'], ['90', 'Last 90 days']])}
        <button type="button" className="btn btn--secondary" onClick={load}>Refresh</button>
      </div>
      {error && <div className="act-error" role="alert">{error} <button type="button" className="btn btn--secondary" onClick={load}>Retry</button></div>}
      {!data && !error && <div className="empty-state" role="status">Loading activity…</div>}
      {data && items.length === 0 && <div className="empty-state">{data.items.length ? 'Nothing matches these filters.' : 'No activity in this window.'}</div>}
      {items.length > 0 && (
        <ol className="act-list">
          {items.map(i => (
            <li key={i.id} className={`act-row act-row--${i.direction} act-row--${i.channel}`}>
              <div className="act-row-head">
                <span className={`sci-chip ${i.direction === 'inbound' ? 'sci-chip--blue' : ''}`}>
                  {i.direction === 'inbound' ? 'Inbound' : 'Outbound'} {i.kind === 'voicemail' ? 'voicemail' : (FEED_KIND_LABEL[i.channel] || i.channel).toLowerCase()}
                </span>
                <button type="button" className="act-name" onClick={() => navigate(`/leads/${i.lead_id}?tab=${i.channel === 'voice' ? 'calls' : 'conversation'}`)}>{i.lead_name}</button>
                {i.is_test && <span className="sci-chip sci-chip--red">Test</span>}
                {i.actor && <span className="sci-chip">{ACTOR_LABEL[i.actor] || i.actor}</span>}
                <span className={`sci-chip ${/fail|undeliver|bounce/i.test(i.result || '') ? 'sci-chip--red' : /deliver|booked|answered|completed|hot/i.test(i.result || '') ? 'sci-chip--green' : ''}`}>{i.result}</span>
                {i.voicemail_left && <span className="sci-chip sci-chip--amber">Voicemail left</span>}
                {i.duration_seconds ? <span className="act-muted">{Math.floor(i.duration_seconds / 60)}m {i.duration_seconds % 60}s</span> : null}
                <time className="act-muted act-when" dateTime={i.at}>{feedWhen(i.at)}</time>
              </div>
              {i.summary && <div className="act-summary">{i.summary}</div>}
              <div className="act-foot">
                {i.has_transcript && <span className="act-muted">Transcript on the contact's Calls tab</span>}
                {i.kind === 'voicemail' && i.has_recording && <span className="act-muted">Recording saved</span>}
                {i.source_label && <span className="act-muted">{i.source_label}</span>}
                {isAdmin && (
                  <button type="button" className="act-tech" aria-expanded={open === i.id} onClick={() => setOpen(open === i.id ? null : i.id)}>
                    {open === i.id ? 'Hide technical detail' : 'Technical detail'}
                  </button>
                )}
              </div>
              {isAdmin && open === i.id && <code className="act-ref">{i.kind} · {i.channel} · record {i.ref}</code>}
            </li>
          ))}
        </ol>
      )}
      {data?.capped && <p className="act-muted">Showing the newest {data.items.length}. Narrow the date range to see further back.</p>}
    </section>
  )
}

export default function Activity() {
  const navigate = useNavigate()
  const [mode, setMode] = useState('all')   // all | sends
  const [items, setItems]       = useState([])
  const [loading, setLoading]   = useState(true)
  const [error, setError]       = useState('')
  const [channel, setChannel]   = useState('all')   // all | sms | email
  const [days, setDays]         = useState(30)
  const [search, setSearch]     = useState('')
  const [today, setToday]       = useState(null)
  const [todayLoading, setTodayLoading] = useState(true)
  const [todayError, setTodayError]     = useState('')

  function loadToday() {
    setTodayLoading(true)
    setTodayError('')
    api.get('/activity/today', { params: { limit: TODAY_LIST_LIMIT } })
      .then((d) => setToday(d && typeof d === 'object' ? d : null))
      .catch((err) => setTodayError(err.message || 'Failed to load'))
      .finally(() => setTodayLoading(false))
  }

  useEffect(() => { loadToday() }, [])

  function load() {
    setLoading(true)
    setError('')
    api.get(`/activity/sent?limit=${FEED_LIMIT}&days=${days}`)
      .then(data => { setItems(Array.isArray(data) ? data : []); setError('') })
      .catch(err => { setError(err.message || 'Failed to load activity feed. Check your connection and try again.'); setItems([]) })
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [days])

  const filtered = items.filter((item) => {
    if (channel !== 'all' && item.channel !== channel) return false
    if (search.trim()) {
      const q = search.toLowerCase()
      return (
        item.lead_name?.toLowerCase().includes(q) ||
        item.lead_email?.toLowerCase().includes(q) ||
        item.lead_phone?.includes(q) ||
        item.subject?.toLowerCase().includes(q) ||
        item.body_preview?.toLowerCase().includes(q)
      )
    }
    return true
  })

  const browserTodayCount = items.filter((i) => {
    if (!i.sent_at) return false
    return new Date(i.sent_at).toDateString() === new Date().toDateString()
  }).length
  // Prefer the server's count (not capped by the 300-row page); fall back to
  // the old browser-side count if /activity/today is unavailable.
  const todayCount = typeof today?.total === 'number' ? today.total : browserTodayCount

  // The feed holds at most FEED_LIMIT rows. When it is full, the counts
  // below are of the most recent FEED_LIMIT, and the labels say so - they
  // read as the whole period's totals before.
  const capped = items.length >= FEED_LIMIT
  const deliveredCount = items.filter((i) => i.delivery_status === 'delivered').length
  const failedCount    = items.filter((i) => ['failed', 'undelivered'].includes(i.delivery_status)).length

  return (
    <div className="sci-ws act-page">
      <div style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 6, flexWrap: 'wrap' }}>
          <h1 className="page-title" style={{ margin: 0 }}>Activity &amp; call history</h1>
          {mode === 'sends' && !loading && <span className="eq-queue-badge">{capped ? `latest ${items.length}` : items.length} sends</span>}
        </div>
        <p className="page-subtitle" style={{ marginTop: 4 }}>
          What actually happened, and when: texts, emails, calls and voicemails, in both directions.
        </p>
        <div className="wq-tabs" role="tablist" aria-label="Activity view" style={{ marginTop: 12 }}>
          <button type="button" role="tab" aria-selected={mode === 'all'} className={mode === 'all' ? 'on' : ''} onClick={() => setMode('all')}>All activity</button>
          <button type="button" role="tab" aria-selected={mode === 'sends'} className={mode === 'sends' ? 'on' : ''} onClick={() => setMode('sends')}>Sends &amp; delivery</button>
        </div>
      </div>

      {mode === 'all' ? <ActivityFeed navigate={navigate} /> : (<>

      {/* Error banner */}
      {error && (
        <div style={{
          marginBottom: 16, padding: '12px 16px',
          border: '1px solid var(--border-danger)', borderRadius: 'var(--radius-md)',
          background: 'var(--signal-red-dim)', color: 'var(--signal-red)',
          display: 'flex', alignItems: 'center', gap: 12,
        }}>
          <span style={{ flex: 1 }}>⚠ {error}</span>
          <button className="btn btn--secondary" style={{ fontSize: 12, padding: '4px 12px' }} onClick={load}>
            ↻ Retry
          </button>
        </div>
      )}

      <TodaySummary
        today={today}
        loading={todayLoading}
        error={todayError}
        onRetry={loadToday}
        navigate={navigate}
      />

      {/* Stats strip */}
      <div className="panel" style={{ display: 'flex', gap: 0, padding: 0, overflow: 'hidden', marginBottom: 16 }}>
        {[
          { label: 'Sent today',   value: todayCount,      color: 'var(--accent)',        icon: '📤' },
          { label: capped ? `Latest ${FEED_LIMIT} sends` : 'Total sends', value: items.length, color: 'var(--text-primary)', icon: '📬' },
          { label: capped ? 'Delivered (of those)' : 'Delivered', value: deliveredCount, color: 'var(--signal-green)', icon: '✓' },
          { label: 'Failed',       value: failedCount,     color: failedCount > 0 ? 'var(--signal-red)' : 'var(--text-secondary)', icon: '✗' },
        ].map((s, i, arr) => (
          <div key={s.label} style={{
            flex: 1, padding: '14px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2,
            borderRight: i < arr.length - 1 ? '1px solid var(--border-subtle)' : 'none',
          }}>
            <div style={{ fontSize: 22, lineHeight: 1, color: s.color }}>{s.icon}</div>
            <strong style={{ fontSize: 22, color: s.color, lineHeight: 1.1 }}>
              {loading ? '—' : s.value}
            </strong>
            <span style={{ fontSize: 11, color: 'var(--text-secondary)', textAlign: 'center' }}>{s.label}</span>
          </div>
        ))}
      </div>

      {/* Controls */}
      <div className="panel" style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center', marginBottom: 16, padding: '12px 16px' }}>
        <input
          type="text"
          placeholder="Search by name, email, phone, or subject…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="search-input"
          aria-label="Search activity"
          style={{
            width: 320, maxWidth: '100%', padding: '8px 12px', fontSize: 13,
            border: '1px solid var(--border-default)', borderRadius: 'var(--radius-sm, 10px)',
            background: 'var(--surface-card)', color: 'var(--text-strong)',
          }}
        />
        <div style={{ display: 'flex', gap: 6 }}>
          {['all', 'sms', 'email'].map((ch) => (
            <button
              key={ch}
              className={`lead-tone-pill ${channel === ch ? 'lead-tone-pill--active' : ''}`}
              onClick={() => setChannel(ch)}
              style={{ fontSize: 12 }}
            >
              {ch === 'all' ? '📬 All' : ch === 'sms' ? '📱 SMS' : '✉️ Email'}
            </button>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 6, marginLeft: 'auto' }}>
          <span style={{ fontSize: 12, color: 'var(--text-secondary)', alignSelf: 'center' }}>Last</span>
          {[7, 14, 30, 90].map((d) => (
            <button
              key={d}
              className={`lead-tone-pill ${days === d ? 'lead-tone-pill--active' : ''}`}
              onClick={() => setDays(d)}
              style={{ fontSize: 12 }}
            >
              {d}d
            </button>
          ))}
        </div>
        <button className="btn btn--secondary" style={{ fontSize: 12, padding: '5px 12px' }} onClick={() => { load(); loadToday() }}>
          ↻ Refresh
        </button>
      </div>

      {/* Activity table */}
      <section className="panel" style={{ padding: 0 }}>
        {loading ? (
          <div className="empty-state">Loading…</div>
        ) : filtered.length === 0 ? (
          <div className="empty-state">
            No sends found for the selected filters.<br />
            <span style={{ fontSize: 13 }}>
              Every SMS and email sent from this workspace is listed here with its delivery status.
              {items.length === 0 && !search ? ' Nothing has been sent in this window yet — try a longer range, or start from ' : ' Try clearing the search or widening the date range.'}
              {items.length === 0 && !search ? <a href="/leads" style={{ color: 'var(--color-primary)', fontWeight: 600 }}>Leads</a> : null}
              {items.length === 0 && !search ? '.' : null}
            </span>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}><table className="data-table">
            <thead>
              <tr>
                <th style={{ width: 36 }}>Ch</th>
                <th>Name</th>
                <th>Contact</th>
                <th>Subject / Preview</th>
                <th style={{ whiteSpace: 'nowrap' }}>Sent</th>
                <th>Delivery</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((item) => {
                const isToday = item.sent_at && new Date(item.sent_at).toDateString() === new Date().toDateString()
                return (
                  <tr key={`${item.channel}-${item.id}`}>
                    <td style={{ textAlign: 'center', fontSize: 16 }}>
                      {item.channel === 'sms' ? '📱' : '✉️'}
                    </td>
                    <td>
                      <span
                        style={{ fontWeight: 600, cursor: 'pointer', color: 'var(--accent)', textDecoration: 'underline' }}
                        onClick={() => navigate(`/leads/${item.lead_id}`)}
                      >
                        {item.lead_name}
                      </span>
                      <AiBadge item={item} />
                      {isToday && (
                        <span style={{
                          marginLeft: 6, fontSize: 10, fontWeight: 700,
                          background: 'var(--pill-success-bg)', color: 'var(--pill-success-fg)',
                          border: '1px solid var(--pill-success-bd)', borderRadius: 3, padding: '1px 5px',
                        }}>
                          TODAY
                        </span>
                      )}
                    </td>
                    <td className="mono" style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
                      {item.channel === 'sms' ? item.lead_phone : item.lead_email}
                    </td>
                    <td style={{ fontSize: 12, maxWidth: 300, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {item.subject
                        ? <><strong style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Subj: </strong>{item.subject}</>
                        : <span style={{ color: 'var(--text-secondary)' }}>{item.body_preview || '—'}</span>}
                    </td>
                    <td style={{ fontSize: 12, color: isToday ? 'var(--signal-green)' : 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                      {formatTime(item.sent_at)}
                    </td>
                    <td>
                      <DeliveryBadge status={item.delivery_status} />
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table></div>
        )}
      </section>
      </>)}
    </div>
  )
}
