import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api/client'
import '../styles/shared.css'

const DELIVERY_CONFIG = {
  delivered:   { label: '✓ Delivered',   color: 'var(--signal-green)',  bg: 'rgba(30,240,168,0.12)',  border: 'rgba(30,240,168,0.3)' },
  sent:        { label: '✓ Sent',         color: 'var(--signal-green)',  bg: 'rgba(30,240,168,0.08)',  border: 'rgba(30,240,168,0.2)' },
  pending:     { label: '⏳ Pending',      color: 'var(--signal-amber)',  bg: 'rgba(255,200,0,0.1)',    border: 'rgba(255,200,0,0.3)' },
  queued:      { label: '⏳ Queued',       color: 'var(--signal-amber)',  bg: 'rgba(255,200,0,0.1)',    border: 'rgba(255,200,0,0.3)' },
  sending:     { label: '⏳ Sending',      color: 'var(--signal-amber)',  bg: 'rgba(255,200,0,0.1)',    border: 'rgba(255,200,0,0.3)' },
  failed:      { label: '✗ Failed',        color: 'var(--signal-red)',    bg: 'rgba(231,76,60,0.1)',    border: 'rgba(231,76,60,0.3)' },
  undelivered: { label: '✗ Undelivered',  color: 'var(--signal-red)',    bg: 'rgba(231,76,60,0.1)',    border: 'rgba(231,76,60,0.3)' },
}

function DeliveryBadge({ status }) {
  const cfg = DELIVERY_CONFIG[status] || DELIVERY_CONFIG.pending
  return (
    <span style={{
      fontSize: 11, borderRadius: 4, padding: '2px 7px', whiteSpace: 'nowrap',
      color: cfg.color, background: cfg.bg, border: `1px solid ${cfg.border}`,
    }}>
      {cfg.label}
    </span>
  )
}

// SS4: rows flagged ai_generated by the backend (send_source vocabulary).
function AiBadge({ item }) {
  if (!item?.ai_generated) return null
  return (
    <span
      title={item.send_source_label ? `AI-generated · ${item.send_source_label}` : 'AI-generated'}
      style={{
        marginLeft: 6, fontSize: 10, fontWeight: 700,
        background: 'rgba(30,168,255,0.15)', color: '#1ea8ff',
        border: '1px solid rgba(30,168,255,0.3)', borderRadius: 3, padding: '1px 5px',
      }}
    >
      AI
    </span>
  )
}

const TODAY_LIST_LIMIT = 50

// SS3: today's sends, counted by the server (/activity/today) against the
// organization's own day boundary rather than filtered from the 30-day page.
function TodaySummary({ today, loading, error, onRetry, navigate }) {
  const [open, setOpen] = useState(false)
  if (loading && !today) {
    return <div className="panel" style={{ marginBottom: 16, padding: '12px 16px', fontSize: 13, color: 'var(--text-secondary)' }}>Loading today…</div>
  }
  if (error && !today) {
    return (
      <div className="panel" style={{ marginBottom: 16, padding: '12px 16px', fontSize: 13, display: 'flex', gap: 12, alignItems: 'center' }}>
        <span style={{ flex: 1, color: 'var(--signal-red)' }}>⚠ Couldn't load today's activity: {error}</span>
        <button className="btn btn--secondary" style={{ fontSize: 12, padding: '4px 12px' }} onClick={onRetry}>↻ Retry</button>
      </div>
    )
  }
  if (!today) return null
  const byChannel = today.by_channel || {}
  const items = today.items || []
  const aiCount = items.filter((i) => i.ai_generated).length
  return (
    <section className="panel" style={{ marginBottom: 16, padding: '12px 16px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
        <strong style={{ fontSize: 14 }}>Today</strong>
        <span style={{ fontSize: 13 }}><strong>{today.total ?? 0}</strong> sent</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>📱 SMS {byChannel.sms || 0}</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>✉️ Email {byChannel.email || 0}</span>
        <span style={{ fontSize: 13, color: 'var(--text-secondary)' }}>
          {today.leads_contacted ?? 0} leads
          {today.contacted_more_than_once > 0 && ` · ${today.contacted_more_than_once} more than once`}
        </span>
        {aiCount > 0 && (
          <span style={{ fontSize: 13, color: '#1ea8ff' }}>
            {aiCount} AI{items.length < (today.total || 0) ? ' (shown)' : ''}
          </span>
        )}
        {today.timezone && (
          <span style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>{today.timezone}</span>
        )}
        {items.length > 0 && (
          <button
            className="btn btn--secondary"
            style={{ fontSize: 12, padding: '4px 12px', marginLeft: 'auto' }}
            onClick={() => setOpen(!open)}
          >
            {open ? 'Hide list ▲' : `Show list ▼`}
          </button>
        )}
      </div>
      {open && items.length > 0 && (
        <div style={{ marginTop: 10, maxHeight: 260, overflowY: 'auto' }}>
          {items.map((item) => (
            <div
              key={`${item.channel}-${item.id}`}
              style={{ display: 'flex', gap: 8, alignItems: 'center', fontSize: 12, padding: '4px 0', borderTop: '1px solid var(--border-subtle)' }}
            >
              <span>{item.channel === 'sms' ? '📱' : '✉️'}</span>
              <span
                style={{ fontWeight: 600, cursor: 'pointer', color: 'var(--accent)' }}
                onClick={() => navigate(`/leads/${item.lead_id}`)}
              >
                {item.lead_name}
              </span>
              <AiBadge item={item} />
              {item.touches_today > 1 && (
                <span style={{ fontSize: 10, color: 'var(--signal-amber)' }}>×{item.touches_today}</span>
              )}
              <span style={{ flex: 1, color: 'var(--text-secondary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {item.preview || '—'}
              </span>
              <span style={{ color: 'var(--text-tertiary)', whiteSpace: 'nowrap' }}>{formatTime(item.sent_at)}</span>
            </div>
          ))}
          {today.returned < today.total && (
            <div style={{ fontSize: 11, color: 'var(--text-tertiary)', paddingTop: 4 }}>
              Showing {today.returned} of {today.total}.
            </div>
          )}
        </div>
      )}
    </section>
  )
}

function formatTime(isoStr) {
  if (!isoStr) return '—'
  const d = new Date(isoStr)
  const now = new Date()
  const today = now.toDateString() === d.toDateString()
  const yesterday = new Date(now - 86400000).toDateString() === d.toDateString()
  const timeStr = d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
  if (today) return `Today ${timeStr}`
  if (yesterday) return `Yesterday ${timeStr}`
  return d.toLocaleDateString([], { month: 'short', day: 'numeric' }) + ' ' + timeStr
}

export default function Activity() {
  const navigate = useNavigate()
  const [items, setItems]       = useState([])
  const [loading, setLoading]   = useState(true)
  const [error, setError]       = useState('')
  const [channel, setChannel]   = useState('all')   // all | sms | email
  const [days, setDays]         = useState(30)
  const [search, setSearch]     = useState('')
  const [today, setToday]       = useState(null)
  const [todayLoading, setTodayLoading] = useState(true)
  const [todayError, setTodayError]     = useState('')

  function loadToday() {
    setTodayLoading(true)
    setTodayError('')
    api.get('/activity/today', { params: { limit: TODAY_LIST_LIMIT } })
      .then((d) => setToday(d && typeof d === 'object' ? d : null))
      .catch((err) => setTodayError(err.message || 'Failed to load'))
      .finally(() => setTodayLoading(false))
  }

  useEffect(() => { loadToday() }, [])

  function load() {
    setLoading(true)
    setError('')
    api.get(`/activity/sent?limit=300&days=${days}`)
      .then(data => { setItems(Array.isArray(data) ? data : []); setError('') })
      .catch(err => { setError(err.message || 'Failed to load activity feed. Check your connection and try again.'); setItems([]) })
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [days])

  const filtered = items.filter((item) => {
    if (channel !== 'all' && item.channel !== channel) return false
    if (search.trim()) {
      const q = search.toLowerCase()
      return (
        item.lead_name?.toLowerCase().includes(q) ||
        item.lead_email?.toLowerCase().includes(q) ||
        item.lead_phone?.includes(q) ||
        item.subject?.toLowerCase().includes(q) ||
        item.body_preview?.toLowerCase().includes(q)
      )
    }
    return true
  })

  const browserTodayCount = items.filter((i) => {
    if (!i.sent_at) return false
    return new Date(i.sent_at).toDateString() === new Date().toDateString()
  }).length
  // Prefer the server's count (not capped by the 300-row page); fall back to
  // the old browser-side count if /activity/today is unavailable.
  const todayCount = typeof today?.total === 'number' ? today.total : browserTodayCount

  const deliveredCount = items.filter((i) => i.delivery_status === 'delivered').length
  const failedCount    = items.filter((i) => ['failed', 'undelivered'].includes(i.delivery_status)).length

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 12, marginBottom: 6 }}>
          <h1 className="page-title" style={{ margin: 0 }}>Activity</h1>
          {!loading && <span className="eq-queue-badge">{items.length} sends</span>}
        </div>
        <p className="page-subtitle" style={{ marginTop: 4 }}>
          Every SMS and email you've sent — with delivery confirmation for SMS.
        </p>
      </div>

      {/* Error banner */}
      {error && (
        <div style={{
          marginBottom: 16, padding: '12px 16px',
          border: '1px solid var(--border-danger)', borderRadius: 'var(--radius-md)',
          background: 'var(--signal-red-dim)', color: 'var(--signal-red)',
          display: 'flex', alignItems: 'center', gap: 12,
        }}>
          <span style={{ flex: 1 }}>⚠ {error}</span>
          <button className="btn btn--secondary" style={{ fontSize: 12, padding: '4px 12px' }} onClick={load}>
            ↻ Retry
          </button>
        </div>
      )}

      <TodaySummary
        today={today}
        loading={todayLoading}
        error={todayError}
        onRetry={loadToday}
        navigate={navigate}
      />

      {/* Stats strip */}
      <div className="panel" style={{ display: 'flex', gap: 0, padding: 0, overflow: 'hidden', marginBottom: 16 }}>
        {[
          { label: 'Sent today',   value: todayCount,      color: 'var(--accent)',        icon: '📤' },
          { label: 'Total sends',  value: items.length,    color: 'var(--text-primary)',  icon: '📬' },
          { label: 'Delivered',    value: deliveredCount,  color: 'var(--signal-green)',  icon: '✓'  },
          { label: 'Failed',       value: failedCount,     color: failedCount > 0 ? 'var(--signal-red)' : 'var(--text-secondary)', icon: '✗' },
        ].map((s, i, arr) => (
          <div key={s.label} style={{
            flex: 1, padding: '14px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2,
            borderRight: i < arr.length - 1 ? '1px solid var(--border-subtle)' : 'none',
          }}>
            <div style={{ fontSize: 22, lineHeight: 1, color: s.color }}>{s.icon}</div>
            <strong style={{ fontSize: 22, color: s.color, lineHeight: 1.1 }}>
              {loading ? '—' : s.value}
            </strong>
            <span style={{ fontSize: 11, color: 'var(--text-secondary)', textAlign: 'center' }}>{s.label}</span>
          </div>
        ))}
      </div>

      {/* Controls */}
      <div className="panel" style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center', marginBottom: 16, padding: '12px 16px' }}>
        <input
          type="text"
          placeholder="Search by name, email, phone, or subject…"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="search-input"
          style={{ width: 320 }}
        />
        <div style={{ display: 'flex', gap: 6 }}>
          {['all', 'sms', 'email'].map((ch) => (
            <button
              key={ch}
              className={`lead-tone-pill ${channel === ch ? 'lead-tone-pill--active' : ''}`}
              onClick={() => setChannel(ch)}
              style={{ fontSize: 12 }}
            >
              {ch === 'all' ? '📬 All' : ch === 'sms' ? '📱 SMS' : '✉️ Email'}
            </button>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 6, marginLeft: 'auto' }}>
          <span style={{ fontSize: 12, color: 'var(--text-secondary)', alignSelf: 'center' }}>Last</span>
          {[7, 14, 30, 90].map((d) => (
            <button
              key={d}
              className={`lead-tone-pill ${days === d ? 'lead-tone-pill--active' : ''}`}
              onClick={() => setDays(d)}
              style={{ fontSize: 12 }}
            >
              {d}d
            </button>
          ))}
        </div>
        <button className="btn btn--secondary" style={{ fontSize: 12, padding: '5px 12px' }} onClick={() => { load(); loadToday() }}>
          ↻ Refresh
        </button>
      </div>

      {/* Activity table */}
      <section className="panel" style={{ padding: 0 }}>
        {loading ? (
          <div className="empty-state">Loading…</div>
        ) : filtered.length === 0 ? (
          <div className="empty-state">No activity found for the selected filters.</div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th style={{ width: 36 }}>Ch</th>
                <th>Name</th>
                <th>Contact</th>
                <th>Subject / Preview</th>
                <th style={{ whiteSpace: 'nowrap' }}>Sent</th>
                <th>Delivery</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((item) => {
                const isToday = item.sent_at && new Date(item.sent_at).toDateString() === new Date().toDateString()
                return (
                  <tr key={`${item.channel}-${item.id}`}>
                    <td style={{ textAlign: 'center', fontSize: 16 }}>
                      {item.channel === 'sms' ? '📱' : '✉️'}
                    </td>
                    <td>
                      <span
                        style={{ fontWeight: 600, cursor: 'pointer', color: 'var(--accent)', textDecoration: 'underline' }}
                        onClick={() => navigate(`/leads/${item.lead_id}`)}
                      >
                        {item.lead_name}
                      </span>
                      <AiBadge item={item} />
                      {isToday && (
                        <span style={{
                          marginLeft: 6, fontSize: 10, fontWeight: 700,
                          background: 'rgba(30,240,168,0.15)', color: 'var(--signal-green)',
                          border: '1px solid rgba(30,240,168,0.3)', borderRadius: 3, padding: '1px 5px',
                        }}>
                          TODAY
                        </span>
                      )}
                    </td>
                    <td className="mono" style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
                      {item.channel === 'sms' ? item.lead_phone : item.lead_email}
                    </td>
                    <td style={{ fontSize: 12, maxWidth: 300, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {item.subject
                        ? <><strong style={{ fontSize: 11, color: 'var(--text-secondary)' }}>Subj: </strong>{item.subject}</>
                        : <span style={{ color: 'var(--text-secondary)' }}>{item.body_preview || '—'}</span>}
                    </td>
                    <td style={{ fontSize: 12, color: isToday ? 'var(--signal-green)' : 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                      {formatTime(item.sent_at)}
                    </td>
                    <td>
                      <DeliveryBadge status={item.delivery_status} />
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </section>
    </div>
  )
}
